learning_templates/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'base'
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('basic_app.urls')),
    path('basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class UserProfileInfo(models.Model):

    # Create a one to one relationship rather than inheriting
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_templates/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
        username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Username"}))
        password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

        class Meta():
            model = User
            fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_templates/basic_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context_dict)

@login_required
def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')


def registration(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.erros, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'user_form': user_form,
                                                           'profile_form': profile_form,
                                                           'registered': registered})


def user_login(request):

    if request.method == "POST":

        # grabs from HTML form
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django authenticates user
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('basic_app:index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print("Username {} and password {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request, 'basic_app/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:index'))

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <ul class="nav">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'basic_app:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:registration' %}">Registration</a>
            </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:login' %}">Login</a>
            </li>
        {% endif %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
    </li>

</ul>

<div class="container">
    {% block body_block %}
    <!--anything outside of this will be inherited when extended-->
    {% endblock %}

</div>
<footer>
    <hr>
    <div class="container">
    {% lorem %}
        </div>
</footer>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
    {% block body_block %}
        <h1>welcome to index</h1>
        <h2>{{ text|cut:"o" }}</h2>
        <h2>{{ number|cut:"00" }}</h2>
    {% endblock %}

learning_templates/templates/basic_app/login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
    {% block body_block %}
    <div class="jumbotron">
        <h1>Please Login</h1>
        <form action="{% url 'basic_app:login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Enter Username">
            <input type="password" name="password" placeholder="Enter Password">

            <input type="submit" name="" value="Login">

        </form>
    </div>


    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}
    <h1>welcome to other</h1>

{% endblock %}

learning_templates/templates/basic_app/registration.html
<!DOCTYPE html>
<head>
    <style>

    </style>
</head>
{% extends 'basic_app/base.html' %}
    {% block body_block %}

    <div class="jumbotron">
        {% if registered %}
         <h1>Thank you for registering</h1>
        {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ user_form.as_p}}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Submit">
        </form>
        {% endif %}
    </div>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
    {% block body_block %}
    <h1>welcome to relative url templates</h1>
{% endblock %}